import { BookData, Testament } from './types';

export const BIBLE_BOOKS: BookData[] = [
  { name: "Genesis", zhName: "創世記", chapters: 50, testament: Testament.OLD, category: "Law" },
  { name: "Exodus", zhName: "出埃及記", chapters: 40, testament: Testament.OLD, category: "Law" },
  { name: "Leviticus", zhName: "利未記", chapters: 27, testament: Testament.OLD, category: "Law" },
  { name: "Numbers", zhName: "民數記", chapters: 36, testament: Testament.OLD, category: "Law" },
  { name: "Deuteronomy", zhName: "申命記", chapters: 34, testament: Testament.OLD, category: "Law" },
  { name: "Joshua", zhName: "約書亞記", chapters: 24, testament: Testament.OLD, category: "History" },
  { name: "Judges", zhName: "士師記", chapters: 21, testament: Testament.OLD, category: "History" },
  { name: "Ruth", zhName: "路得記", chapters: 4, testament: Testament.OLD, category: "History" },
  { name: "1 Samuel", zhName: "撒母耳記上", chapters: 31, testament: Testament.OLD, category: "History" },
  { name: "2 Samuel", zhName: "撒母耳記下", chapters: 24, testament: Testament.OLD, category: "History" },
  { name: "1 Kings", zhName: "列王紀上", chapters: 22, testament: Testament.OLD, category: "History" },
  { name: "2 Kings", zhName: "列王紀下", chapters: 25, testament: Testament.OLD, category: "History" },
  { name: "1 Chronicles", zhName: "歷代志上", chapters: 29, testament: Testament.OLD, category: "History" },
  { name: "2 Chronicles", zhName: "歷代志下", chapters: 36, testament: Testament.OLD, category: "History" },
  { name: "Ezra", zhName: "以斯拉記", chapters: 10, testament: Testament.OLD, category: "History" },
  { name: "Nehemiah", zhName: "尼希米記", chapters: 13, testament: Testament.OLD, category: "History" },
  { name: "Esther", zhName: "以斯帖記", chapters: 10, testament: Testament.OLD, category: "History" },
  { name: "Job", zhName: "約伯記", chapters: 42, testament: Testament.OLD, category: "Wisdom" },
  { name: "Psalms", zhName: "詩篇", chapters: 150, testament: Testament.OLD, category: "Wisdom" },
  { name: "Proverbs", zhName: "箴言", chapters: 31, testament: Testament.OLD, category: "Wisdom" },
  { name: "Ecclesiastes", zhName: "傳道書", chapters: 12, testament: Testament.OLD, category: "Wisdom" },
  { name: "Song of Solomon", zhName: "雅歌", chapters: 8, testament: Testament.OLD, category: "Wisdom" },
  { name: "Isaiah", zhName: "以賽亞書", chapters: 66, testament: Testament.OLD, category: "Prophecy" },
  { name: "Jeremiah", zhName: "耶利米書", chapters: 52, testament: Testament.OLD, category: "Prophecy" },
  { name: "Lamentations", zhName: "耶利米哀歌", chapters: 5, testament: Testament.OLD, category: "Prophecy" },
  { name: "Ezekiel", zhName: "以西結書", chapters: 48, testament: Testament.OLD, category: "Prophecy" },
  { name: "Daniel", zhName: "但以理書", chapters: 12, testament: Testament.OLD, category: "Prophecy" },
  { name: "Hosea", zhName: "何西阿書", chapters: 14, testament: Testament.OLD, category: "Prophecy" },
  { name: "Joel", zhName: "約珥書", chapters: 3, testament: Testament.OLD, category: "Prophecy" },
  { name: "Amos", zhName: "阿摩司書", chapters: 9, testament: Testament.OLD, category: "Prophecy" },
  { name: "Obadiah", zhName: "俄巴底亞書", chapters: 1, testament: Testament.OLD, category: "Prophecy" },
  { name: "Jonah", zhName: "約拿書", chapters: 4, testament: Testament.OLD, category: "Prophecy" },
  { name: "Micah", zhName: "彌迦書", chapters: 7, testament: Testament.OLD, category: "Prophecy" },
  { name: "Nahum", zhName: "那鴻書", chapters: 3, testament: Testament.OLD, category: "Prophecy" },
  { name: "Habakkuk", zhName: "哈巴谷書", chapters: 3, testament: Testament.OLD, category: "Prophecy" },
  { name: "Zephaniah", zhName: "西番雅書", chapters: 3, testament: Testament.OLD, category: "Prophecy" },
  { name: "Haggai", zhName: "哈該書", chapters: 2, testament: Testament.OLD, category: "Prophecy" },
  { name: "Zechariah", zhName: "撒迦利亞書", chapters: 14, testament: Testament.OLD, category: "Prophecy" },
  { name: "Malachi", zhName: "瑪拉基書", chapters: 4, testament: Testament.OLD, category: "Prophecy" },
  { name: "Matthew", zhName: "馬太福音", chapters: 28, testament: Testament.NEW, category: "Gospel" },
  { name: "Mark", zhName: "馬可福音", chapters: 16, testament: Testament.NEW, category: "Gospel" },
  { name: "Luke", zhName: "路加福音", chapters: 24, testament: Testament.NEW, category: "Gospel" },
  { name: "John", zhName: "約翰福音", chapters: 21, testament: Testament.NEW, category: "Gospel" },
  { name: "Acts", zhName: "使徒行傳", chapters: 28, testament: Testament.NEW, category: "History" },
  { name: "Romans", zhName: "羅馬書", chapters: 16, testament: Testament.NEW, category: "Epistle" },
  { name: "1 Corinthians", zhName: "哥林多前書", chapters: 16, testament: Testament.NEW, category: "Epistle" },
  { name: "2 Corinthians", zhName: "哥林多後書", chapters: 13, testament: Testament.NEW, category: "Epistle" },
  { name: "Galatians", zhName: "加拉太書", chapters: 6, testament: Testament.NEW, category: "Epistle" },
  { name: "Ephesians", zhName: "以弗所書", chapters: 6, testament: Testament.NEW, category: "Epistle" },
  { name: "Philippians", zhName: "腓立比書", chapters: 4, testament: Testament.NEW, category: "Epistle" },
  { name: "Colossians", zhName: "歌羅西書", chapters: 4, testament: Testament.NEW, category: "Epistle" },
  { name: "1 Thessalonians", zhName: "帖撒羅尼迦前書", chapters: 5, testament: Testament.NEW, category: "Epistle" },
  { name: "2 Thessalonians", zhName: "帖撒羅尼迦後書", chapters: 3, testament: Testament.NEW, category: "Epistle" },
  { name: "1 Timothy", zhName: "提摩太前書", chapters: 6, testament: Testament.NEW, category: "Epistle" },
  { name: "2 Timothy", zhName: "提摩太後書", chapters: 4, testament: Testament.NEW, category: "Epistle" },
  { name: "Titus", zhName: "提多書", chapters: 3, testament: Testament.NEW, category: "Epistle" },
  { name: "Philemon", zhName: "腓利門書", chapters: 1, testament: Testament.NEW, category: "Epistle" },
  { name: "Hebrews", zhName: "希伯來書", chapters: 13, testament: Testament.NEW, category: "Epistle" },
  { name: "James", zhName: "雅各書", chapters: 5, testament: Testament.NEW, category: "Epistle" },
  { name: "1 Peter", zhName: "彼得前書", chapters: 5, testament: Testament.NEW, category: "Epistle" },
  { name: "2 Peter", zhName: "彼得後書", chapters: 3, testament: Testament.NEW, category: "Epistle" },
  { name: "1 John", zhName: "約翰一書", chapters: 5, testament: Testament.NEW, category: "Epistle" },
  { name: "2 John", zhName: "約翰二書", chapters: 1, testament: Testament.NEW, category: "Epistle" },
  { name: "3 John", zhName: "約翰三書", chapters: 1, testament: Testament.NEW, category: "Epistle" },
  { name: "Jude", zhName: "猶大書", chapters: 1, testament: Testament.NEW, category: "Epistle" },
  { name: "Revelation", zhName: "啟示錄", chapters: 22, testament: Testament.NEW, category: "Prophecy" },
];

export const TOTAL_CHAPTERS = 1189;